# Generated by Django 4.1.5 on 2023-02-01 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0003_post_username_alter_post_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 1, 16, 35, 16, 177292, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
