# Generated by Django 4.1.5 on 2023-02-02 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0006_alter_post_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="LikePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.CharField(max_length=600)),
                ("username", models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 2, 12, 27, 55, 601817, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
