# Generated by Django 4.1.5 on 2023-02-02 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0007_likepost_alter_post_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowerCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follower", models.CharField(max_length=40)),
                ("user", models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 2, 15, 47, 25, 656185, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
